package com.sangtq.model.forecast

data class Hour(
    val chance_of_rain: Int = 0,
    val chance_of_snow: Int = 0,
    val cloud: Int = 0,
    val condition: Condition ? = null,
    val dewpoInt_c: Double = 0.0,
    val dewpoInt_f: Double = 0.0,
    val feelslike_c: Double = 0.0,
    val feelslike_f: Double = 0.0,
    val gust_kph: Double = 0.0,
    val gust_mph: Double = 0.0,
    val heatindex_c: Double = 0.0,
    val heatindex_f: Double = 0.0,
    val humidity: Int = 0,
    val is_day: Int = 0,
    val precip_in: Double = 0.0,
    val precip_mm: Double = 0.0,
    val pressure_in: Double = 0.0,
    val pressure_mb: Int = 0,
    val snow_cm: Int = 0,
    val temp_c: Double = 0.0,
    val temp_f: Double = 0.0,
    val time: String = "",
    val time_epoch: Long = 0,
    val uv: Int = 0,
    val vis_km: Int = 0,
    val vis_miles: Int = 0,
    val will_it_rain: Int = 0,
    val will_it_snow: Int = 0,
    val wind_degree: Int = 0,
    val wind_dir: String = "",
    val wind_kph: Double = 0.0,
    val wind_mph: Double = 0.0,
    val windchill_c: Double = 0.0,
    val windchill_f: Double = 0.0,
    var isNow: Boolean = false,
)